#!/usr/bin/env python3
"""Compare the live skills.sh listing against this repo and ask for a rescan if it lags.

skills.sh exposes no publish, sync, or refresh endpoint -- Vercel's crawler picks
repos up on its own cadence, and the documented remedy when a listing goes stale is
an issue on vercel-labs/skills. So after a release this script checks whether the
public listing already reflects what shipped, and files that request when it does not.

The repo page at https://skills.sh/<owner>/<repo> links exactly the skill slugs the
crawler currently knows about, which is the signal used here. Per-skill URLs are not
usable for this: skills.sh answers 200 with a rendered shell even for a slug that
does not exist, so their status codes prove nothing.

Filing is opt-in and needs SKILLS_SH_RESCAN_TOKEN -- a token that can open issues on
vercel-labs/skills, which the workflow's repo-scoped GITHUB_TOKEN cannot do. Without
it the script reports the drift and stops, which is also what --dry-run does.

This never fails the release. An unreachable skills.sh, a changed page layout, or a
missing token are all reported and exited 0; a stale listing is cosmetic, and a red
release job would be a worse outcome than a late listing.

NOTE: this file lives only in the distribution repo. A republish from MajarrahCore
overwrites .github/, so port it to distribution/majarrah-marketplace/ to keep it.
"""
import argparse
import json
import os
import re
import subprocess
import sys
import urllib.error
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(Path(__file__).resolve().parent))

from sync_readme_skills_sh import discovered_skills, repo_slug  # noqa: E402

RESCAN_REPO = "vercel-labs/skills"
TIMEOUT = 30

# Next.js route assets that share the /<owner>/<repo>/ prefix but are not skills.
NON_SKILL_PATHS = {
    "opengraph-image", "twitter-image", "icon", "apple-icon", "favicon",
    "sitemap", "robots",
}


def fetch(url: str) -> str | None:
    request = urllib.request.Request(
        url, headers={"User-Agent": "majarrah-marketplace-release/1.0"}
    )
    try:
        with urllib.request.urlopen(request, timeout=TIMEOUT) as response:
            return response.read().decode("utf-8", "replace")
    except (urllib.error.URLError, TimeoutError, OSError) as error:
        print(f"warning: could not reach {url}: {error}")
        return None


def indexed_skills(owner: str, repo: str) -> set[str] | None:
    """Skill slugs skills.sh currently lists for this repo, or None if unreadable."""
    page = fetch(f"https://skills.sh/{owner}/{repo}")
    if page is None:
        return None
    pattern = re.compile(
        rf"/{re.escape(owner)}/{re.escape(repo)}/([A-Za-z0-9][A-Za-z0-9._-]*)",
        re.IGNORECASE,
    )
    return {
        slug for slug in pattern.findall(page)
        if "." not in slug and slug.lower() not in NON_SKILL_PATHS
    }


def issue_body(owner: str, repo: str, missing: list[str], delisted: list[str]) -> str:
    lines = [
        f"The skills.sh listing for [`{owner}/{repo}`]"
        f"(https://skills.sh/{owner}/{repo}) is behind the repository after a "
        "release, so the indexed snapshot no longer matches what the repo ships.",
        "",
    ]
    if missing:
        lines += ["**In the repo but not listed**", ""]
        lines += [f"- `{name}`" for name in missing] + [""]
    if delisted:
        lines += ["**Listed but no longer in the repo**", ""]
        lines += [f"- `{name}`" for name in delisted] + [""]
    lines += [
        "Every skill above lives at `plugins/<plugin>/skills/<skill>/SKILL.md` on the "
        f"default branch of https://github.com/{owner}/{repo}.",
        "",
        "Could this repo be rescanned so the listing matches? Thanks!",
        "",
        "---",
        "_Generated by [Claude Code](https://claude.ai/code)_",
    ]
    return "\n".join(lines)


def existing_request(owner: str, repo: str, env: dict) -> str | None:
    """URL of an open rescan issue already filed for this repo, if any."""
    result = subprocess.run(
        ["gh", "issue", "list", "-R", RESCAN_REPO, "--state", "open",
         "--search", f"{repo} in:title", "--json", "title,url", "--limit", "50"],
        capture_output=True, text=True, env=env,
    )
    if result.returncode != 0:
        print(f"warning: could not list existing issues: {result.stderr.strip()}")
        return None
    for issue in json.loads(result.stdout or "[]"):
        if f"{owner}/{repo}".lower() in issue["title"].lower():
            return issue["url"]
    return None


def file_request(owner: str, repo: str, title: str, body: str, env: dict) -> int:
    duplicate = existing_request(owner, repo, env)
    if duplicate:
        print(f"rescan already requested at {duplicate} - not filing another")
        return 0
    result = subprocess.run(
        ["gh", "issue", "create", "-R", RESCAN_REPO, "--title", title, "--body", body],
        capture_output=True, text=True, env=env,
    )
    if result.returncode != 0:
        print(f"warning: could not file rescan request: {result.stderr.strip()}")
        return 0
    print(f"filed rescan request: {result.stdout.strip()}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--dry-run", action="store_true",
        help="report drift without filing an issue",
    )
    args = parser.parse_args()

    owner, repo = repo_slug()
    local = set(discovered_skills())
    if not local:
        print("no SKILL.md files found under plugins/ - nothing to compare")
        return 0

    listed = indexed_skills(owner, repo)
    if listed is None:
        print("skipping rescan check - skills.sh listing could not be read")
        return 0
    if not listed:
        # Either the repo is genuinely unindexed or the page layout changed under
        # us. Both look identical from here, and guessing wrong means opening a
        # bogus issue on someone else's repo, so report and stop.
        print(f"warning: no skill links found on https://skills.sh/{owner}/{repo} - "
              "not filing a rescan request; check the listing by hand")
        return 0

    missing = sorted(local - listed)
    delisted = sorted(listed - local)
    if not missing and not delisted:
        print(f"skills.sh listing is current ({len(local)} skills)")
        return 0

    title = f"Request rescan: {owner}/{repo} - listing is behind the repo"
    body = issue_body(owner, repo, missing, delisted)
    print(f"skills.sh drift - missing: {missing or 'none'}; delisted: {delisted or 'none'}")

    token = os.environ.get("SKILLS_SH_RESCAN_TOKEN", "").strip()
    if args.dry_run or not token:
        reason = "--dry-run" if args.dry_run else "SKILLS_SH_RESCAN_TOKEN is not set"
        print(f"not filing a rescan request ({reason}). Would open on {RESCAN_REPO}:")
        print(f"  {title}")
        return 0
    return file_request(owner, repo, title, body, {**os.environ, "GH_TOKEN": token})


if __name__ == "__main__":
    sys.exit(main())
